# Generated by Django 4.2.5 on 2023-11-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('mapper', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('map_type', models.CharField(max_length=255)),
                ('total_length', models.IntegerField()),
                ('play_count', models.IntegerField()),
                ('favourite_count', models.IntegerField()),
                ('star_difficulty', models.FloatField()),
                ('bpm', models.FloatField()),
                ('ar', models.FloatField()),
                ('od', models.FloatField()),
                ('hp', models.FloatField()),
                ('cs', models.FloatField()),
                ('submit_date', models.DateField()),
                ('song_id', models.IntegerField()),
            ],
        ),
    ]
